name: Prettier

on:
  pull_request:
    branches:
      - "*"

jobs:
  prettier:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - uses: creyD/prettier_action@v4.0
        name: "prettify files | pull request"
        with:
          prettier_options: --write **/*.{js,css,json} --use-tabs --trailing-comma none --arrow-parens avoid
          commit_message: "style: prettify files"
          only_changed: true
