name: Prettier

on:
  pull_request:
    branches:
      - "*"

jobs:
  prettier:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - uses: creyD/prettier_action@v4.0
        name: "chore: prettify files (Pull Request)"
        with:
          prettier_options: --check **/*.{js,css,json} --use-tabs --trailing-comma none --arrow-parens avoid
          only_changed: true
        if: ${{ github.event_name == 'pull_request' && github.event_name != 'push' }}
